# Generated by Django 4.2.3 on 2023-12-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('opt1', models.CharField(max_length=30)),
                ('opt2', models.CharField(max_length=30)),
                ('opt3', models.CharField(max_length=30)),
                ('opt1_count', models.IntegerField(default=0)),
                ('opt2_count', models.IntegerField(default=0)),
                ('opt3_count', models.IntegerField(default=0)),
            ],
        ),
    ]
